# Generated by Django 3.0.7 on 2020-07-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='Question_No',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
