# Generated by Django 3.0.7 on 2020-08-04 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_questions_question_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answerset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer1', models.CharField(max_length=100)),
                ('Answer2', models.CharField(max_length=100)),
                ('Answer3', models.CharField(max_length=100)),
                ('Answer4', models.CharField(max_length=100)),
                ('Answer5', models.CharField(max_length=100)),
                ('Answer6', models.CharField(max_length=100)),
                ('Answer7', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
