# Generated by Django 3.0.7 on 2020-08-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answerset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerset',
            name='Answer1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='Answer2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='Answer3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='Answer4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='Answer5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='Answer6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='Answer7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
