# Generated by Django 3.0.7 on 2020-08-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_questions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerset',
            name='correct1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='answerset',
            name='correct2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='answerset',
            name='correct3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='answerset',
            name='correct4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='answerset',
            name='correct5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='answerset',
            name='correct6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='answerset',
            name='correct7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
