# Generated by Django 3.0.7 on 2020-08-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200806_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerset',
            name='correct1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='correct2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='correct3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='correct4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='correct5',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='correct6',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='correct7',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
