# Generated by Django 3.0.7 on 2020-08-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200806_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerset',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
